### ISSUE TITLE
Controller needs to be identified in body of notifications

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/NotificationProxy#7]
It is assumed that multiple controllers are operating in parallel.
Consequently, the instance of controller needs to be identified inside controller related notifications.

Potential solution:
The ControllerIdentifier is added in front of the object-id-ref.

But, where is this information coming from?

**Comment by openBackhaul** [comment]
It is assumed that a controller-id attribute will be added.
````
  example:
    urn-ietf-params-xml-ns-netconf-notification-1.0:notification:
      controller-id: 'odl-1'
      event-time: '2023-07-11T08:21:50.526721696Z'
      urn-opendaylight-params-xml-ns-yang-controller-md-sal-remote:data-changed-notification:
        data-change-event:
          - store: 'operation'
            path: '/urn-TBD-p ... ection-status'
            operation: 'updated'
            data:
              netconf-node-topology:connection-status: 'connecting'
````
Zia got asked to inform, if different solution would be agreed or implemented.
