### ISSUE TITLE
Correct uuid in NotificationProxy-httpClient

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/NotificationProxy#9]
uuid of */v1/listen-to-controllers* is *-bm-*, but should be *-im-*:

```
  - http-client:
      application-name: NotificationProxy
      release-number: 1.0.0
      uuid: np-1-0-0-http-c-np-1-0-0-000
    tcp-client:
      remote-protocol: http
      ip-address: 1.1.4.11
      tcp-port: 4011
      uuid: np-1-0-0-tcp-c-np-1-0-0-000
    operation-clients:
      own-oam:
        basic:
        individual:
          - operation-name: /v1/listen-to-controllers
            uuid: np-1-0-0-op-c-bm-np-1-0-0-000
      service:
        basic:
        individual:
```
