### ISSUE TITLE
Add operation keys to services in serviceList

### ISSUE THREAD

**Issue by kmohr-soprasteria** [openBackhaul/NotificationProxy#91]
the basic and individual services in serviceList have an entry for the operation key
(used by the configFile generator).

example:
```
    service:
      basic:
        - operation-name: /v1/start-application-in-generic-representation
          uuid: mwdi-2-0-1-op-s-bs-000
          operation-key: n.a.
```

The operation-key lines need to be added
